### ISSUE TITLE
Tests & output incorrectly centered

### ISSUE THREAD

**Issue by seanhagen** [robherley/go-test-action#18]
![image](https://github.com/robherley/go-test-action/assets/444767/6b01a04b-70f6-4966-ba4e-af18bef3dcda)

Not a huge issue, but the text is centered and makes it a bit harder to read.

**Comment by robherley** [comment]
👋 @seanhagen what browser/os are you using? also is your repo public?

on macos/arc (chromium) it's rendering correctly: https://github.com/robherley/go-test-example/actions/runs/8862141964

![Image](https://github.com/robherley/go-test-action/assets/16991201/005c5be6-ed84-40fe-bce3-e8bc221c9ac0)

if I can repro, i'll try to move some tags around to fix it 👍

**Comment by kemitche** [comment]
Also seeing this, on Windows 11/Firefox. (Private repo, but a very basic, single test case)

![image](https://github.com/robherley/go-test-action/assets/849933/e7dc291d-7a7d-4456-b64b-82a06dba8e2d)

Workflow snippet (nothing major here other than use of `omit: untested`):

```yaml
  tests:
    name: Run test cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run tests
        with:
          omit: untested
```
